In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame(np.random.randint(15,100,(20,4)),columns=["A","B","C","D"])
df

     A   B   C   D
0   61  25  86  94
1   48  48  31  20
2   47  84  92  20
3   27  91  72  41
4   17  82  43  79
5   99  90  76  57
6   50  15  78  18
7   78  63  38  55
8   52  90  60  34
9   52  74  20  26
10  29  97  74  74
11  19  25  21  67
12  56  81  41  82
13  26  93  34  29
14  18  94  97  82
15  99  31  72  45
16  16  36  78  26
17  34  21  75  87
18  78  16  86  95
19  21  56  88  64

In [4]:
df.apply(sum)

A     927
B    1212
C    1262
D    1095
dtype: int64

In [5]:
df["total"]=df.apply(sum,axis=1)

In [6]:
df

     A   B   C   D  total
0   61  25  86  94    266
1   48  48  31  20    147
2   47  84  92  20    243
3   27  91  72  41    231
4   17  82  43  79    221
5   99  90  76  57    322
6   50  15  78  18    161
7   78  63  38  55    234
8   52  90  60  34    236
9   52  74  20  26    172
10  29  97  74  74    274
11  19  25  21  67    132
12  56  81  41  82    260
13  26  93  34  29    182
14  18  94  97  82    291
15  99  31  72  45    247
16  16  36  78  26    156
17  34  21  75  87    217
18  78  16  86  95    275
19  21  56  88  64    229

In [10]:
df["Avg"]=df.apply("mean",axis=1)

In [11]:
df

     A   B   C   D  total    Avg
0   61  25  86  94    266  106.4
1   48  48  31  20    147   58.8
2   47  84  92  20    243   97.2
3   27  91  72  41    231   92.4
4   17  82  43  79    221   88.4
5   99  90  76  57    322  128.8
6   50  15  78  18    161   64.4
7   78  63  38  55    234   93.6
8   52  90  60  34    236   94.4
9   52  74  20  26    172   68.8
10  29  97  74  74    274  109.6
11  19  25  21  67    132   52.8
12  56  81  41  82    260  104.0
13  26  93  34  29    182   72.8
14  18  94  97  82    291  116.4
15  99  31  72  45    247   98.8
16  16  36  78  26    156   62.4
17  34  21  75  87    217   86.8
18  78  16  86  95    275  110.0
19  21  56  88  64    229   91.6

In [12]:
df.apply(lambda x:x["A"]+x["B"]+x["C"],axis=1)

0     172.0
1     127.0
2     223.0
3     190.0
4     142.0
5     265.0
6     143.0
7     179.0
8     202.0
9     146.0
10    200.0
11     65.0
12    178.0
13    153.0
14    209.0
15    202.0
16    130.0
17    130.0
18    180.0
19    165.0
dtype: float64

In [14]:
df["Grade"]=df.apply(lambda x:"Fail" if x["A"]<35 or x["B"]<35 or x["C"]<35 or x["D"]<35 else "pass",axis=1)

In [15]:
df

     A   B   C   D  total    Avg Grade
0   61  25  86  94    266  106.4  Fail
1   48  48  31  20    147   58.8  Fail
2   47  84  92  20    243   97.2  Fail
3   27  91  72  41    231   92.4  Fail
4   17  82  43  79    221   88.4  Fail
5   99  90  76  57    322  128.8  pass
6   50  15  78  18    161   64.4  Fail
7   78  63  38  55    234   93.6  pass
8   52  90  60  34    236   94.4  Fail
9   52  74  20  26    172   68.8  Fail
10  29  97  74  74    274  109.6  Fail
11  19  25  21  67    132   52.8  Fail
12  56  81  41  82    260  104.0  pass
13  26  93  34  29    182   72.8  Fail
14  18  94  97  82    291  116.4  Fail
15  99  31  72  45    247   98.8  Fail
16  16  36  78  26    156   62.4  Fail
17  34  21  75  87    217   86.8  Fail
18  78  16  86  95    275  110.0  Fail
19  21  56  88  64    229   91.6  Fail

In [16]:
def result(x):
    if x>90:
        return "A"
    if x>80:
        return "B"
    if x>70:
        return "C"
    if x>60:
        return "D"
    return "FAIL"

In [17]:
df["Avg"].apply(result)

0        A
1     FAIL
2        A
3        A
4        B
5        A
6        D
7        A
8        A
9        D
10       A
11    FAIL
12       A
13       C
14       A
15       A
16       D
17       B
18       A
19       A
Name: Avg, dtype: object

In [18]:
df.apply([sum,"mean"])

,A,B,C,D,total,Avg,Grade
sum,927.00,1212.0,1262.0,1095.00,4496.0,1798.40,FailFailFailFailFailpassFailpassFailFailFailFa...
mean,46.35,60.6,63.1,54.75,224.8,89.92,NaN

In [21]:
df.corr()

              A         B         C         D     total       Avg
A      1.000000 -0.179454  0.059617  0.008032  0.435409  0.435409
B     -0.179454  1.000000 -0.106309 -0.138426  0.373502  0.373502
C      0.059617 -0.106309  1.000000  0.234090  0.568735  0.568735
D      0.008032 -0.138426  0.234090  1.000000  0.553185  0.553185
total  0.435409  0.373502  0.568735  0.553185  1.000000  1.000000
Avg    0.435409  0.373502  0.568735  0.553185  1.000000  1.000000