In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.Series([10,20,30])
print(df)

0    10
1    20
2    30
dtype: int64

In [3]:
print(type(df))

<class 'pandas.core.series.Series'>

In [4]:
dk=pd.Series((10,20,30))
print(dk)

0    10
1    20
2    30
dtype: int64

In [5]:
dv=pd.Series({'A':10,'B':20,'C':30})
print(dv)

A    10
B    20
C    30
dtype: int64

In [6]:
df=pd.Series(np.array([10,20,30]))
print(df)

0    10
1    20
2    30
dtype: int32

In [7]:
df=pd.Series(np.array([10,20,30]),index=['p','q','r'])
print(df)

p    10
q    20
r    30
dtype: int32

In [10]:
df=pd.DataFrame([['B9','B8','B7'],['10','9','8'],['7000','3000','5000']])
print(df)

      0     1     2
0    B9    B8    B7
1    10     9     8
2  7000  3000  5000

In [13]:
df=pd.DataFrame([['B9','B8','B7'],['10','9','8'],['7000','3000','5000']],index=['a','b','c'],columns=['p','q','r'])
print(df)

      p     q     r
a    B9    B8    B7
b    10     9     8
c  7000  3000  5000

In [14]:
df=pd.DataFrame({'A':[7,8,9],'B':[11,12,13],'C':['X','Y','Z']},index=['p','q','r'])
print(df)

   A   B  C
p  7  11  X
q  8  12  Y
r  9  13  Z

In [15]:
df=pd.DataFrame([{'name':'Vishal','m':10},{'name':'yug','m':9}])
print(df)

     name   m
0  Vishal  10
1     yug   9

In [17]:
df=pd.read_csv('train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [18]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [19]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [20]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [21]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [22]:
df.shape

(891, 12)

In [25]:
df.size #number of row maltipay by number of column

10692

In [27]:
df=pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]],index=['P','Q','R'],columns=['A','B','C'])
print(df)

    A   B   C
P  10  20  30
Q  40  50  60
R  70  80  90

In [30]:
df['A']

P    10
Q    40
R    70
Name: A, dtype: int64

In [31]:
df['C']

P    30
Q    60
R    90
Name: C, dtype: int64

In [33]:
df[['A','B']]

    A   B
P  10  20
Q  40  50
R  70  80

In [34]:
df.loc['P']

A    10
B    20
C    30
Name: P, dtype: int64

In [35]:
df.loc['P','B']

20

In [37]:
df.loc[:,'C']

P    30
Q    60
R    90
Name: C, dtype: int64

In [39]:
df.loc['P':'Q','A':'B']

    A   B
P  10  20
Q  40  50

In [41]:
df.loc[['P','Q'],['B','C']]

    B   C
P  20  30
Q  50  60

In [42]:
df.loc[['P','R'],['A','C']]

    A   C
P  10  30
R  70  90

In [45]:
df.loc['Q','B']=70

In [46]:
print(df)

    A   B   C
P  10  20  30
Q  40  70  60
R  70  80  90

In [47]:
df.loc['X']=[70,90,100]
print(df)

    A   B    C
P  10  20   30
Q  40  70   60
R  70  80   90
X  70  90  100

In [48]:
df['D']=10

In [49]:
print(df)

    A   B    C   D
P  10  20   30  10
Q  40  70   60  10
R  70  80   90  10
X  70  90  100  10

In [50]:
df=pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]])
print(df)

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [51]:
df.iloc[1,1]

50

In [54]:
df.iloc[1]

0    40
1    50
2    60
Name: 1, dtype: int64

In [55]:
df.iloc[:,1]

0    20
1    50
2    80
Name: 1, dtype: int64

In [56]:
df.iloc[0:2,0:2]

    0   1
0  10  20
1  40  50

In [61]:
df.iloc[:,1:3]

    1   2
0  20  30
1  50  60
2  80  90

In [86]:
df=pd.read_csv('train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [87]:
df=df.set_index('Name')

In [88]:
print(df)

                                                    PassengerId  Survived  \
Name
Braund, Mr. Owen Harris                                       1         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Allen, Mr. William Henry                                      5         0
...                                                         ...       ...
Montvila, Rev. Juozas                                       887         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0
Behr, Mr. Karl Howell                                       890         1
Dooley, Mr. Patrick                                         891         0

                                                    Pclass     Sex   Age  \
Name
Braund, Mr. Owen Harris                                  3    male  22.0
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Allen, Mr. William Henry                                 3    male  35.0
...                                                    ...     ...   ...
Montvila, Rev. Juozas                                    2    male  27.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN
Behr, Mr. Karl Howell                                    1    male  26.0
Dooley, Mr. Patrick                                      3    male  32.0

                                                    SibSp  Parch  \
Name
Braund, Mr. Owen Harris                                 1      0
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Allen, Mr. William Henry                                0      0
...                                                   ...    ...
Montvila, Rev. Juozas                                   0      0
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2
Behr, Mr. Karl Howell                                   0      0
Dooley, Mr. Patrick                                     0      0

                                                              Ticket     Fare  \
Name
Braund, Mr. Owen Harris                                    A/5 21171   7.2500
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Allen, Mr. William Henry                                      373450   8.0500
...                                                              ...      ...
Montvila, Rev. Juozas                                         211536  13.0000
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500
Behr, Mr. Karl Howell                                         111369  30.0000
Dooley, Mr. Patrick                                           370376   7.7500

                                                   Cabin Embarked
Name
Braund, Mr. Owen Harris                              NaN        S
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C
Heikkinen, Miss. Laina                               NaN        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S
Allen, Mr. William Henry                             NaN        S
...                                                  ...      ...
Montvila, Rev. Juozas                                NaN        S
Graham, Miss. Margaret Edith                         B42        S
Johnston, Miss. Catherine Helen "Carrie"             NaN        S
Behr, Mr. Karl Howell                               C148        C
Dooley, Mr. Patrick                                  NaN        Q

[891 rows x 11 columns]

In [89]:
df=df.reset_index()

In [91]:
print(df)

                                                  Name  PassengerId  Survived  \
0                              Braund, Mr. Owen Harris            1         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...            2         1
2                               Heikkinen, Miss. Laina            3         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)            4         1
4                             Allen, Mr. William Henry            5         0
..                                                 ...          ...       ...
886                              Montvila, Rev. Juozas          887         0
887                       Graham, Miss. Margaret Edith          888         1
888           Johnston, Miss. Catherine Helen "Carrie"          889         0
889                              Behr, Mr. Karl Howell          890         1
890                                Dooley, Mr. Patrick          891         0

     Pclass     Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
0         3    male  22.0      1      0         A/5 21171   7.2500   NaN
1         1  female  38.0      1      0          PC 17599  71.2833   C85
2         3  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN
3         1  female  35.0      1      0            113803  53.1000  C123
4         3    male  35.0      0      0            373450   8.0500   NaN
..      ...     ...   ...    ...    ...               ...      ...   ...
886       2    male  27.0      0      0            211536  13.0000   NaN
887       1  female  19.0      0      0            112053  30.0000   B42
888       3  female   NaN      1      2        W./C. 6607  23.4500   NaN
889       1    male  26.0      0      0            111369  30.0000  C148
890       3    male  32.0      0      0            370376   7.7500   NaN

    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
886        S
887        S
888        S
889        C
890        Q

[891 rows x 12 columns]

In [92]:
df.head(3)

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [93]:
df.tail(5)

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.00,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.00,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.00,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.75,NaN,Q

In [94]:
df.sample(7)

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
319,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",320,1,1,female,40.0,1,1,16966,134.5000,E34,C
867,"Roebling, Mr. Washington Augustus II",868,0,1,male,31.0,0,0,PC 17590,50.4958,A24,S
508,"Olsen, Mr. Henry Margido",509,0,3,male,28.0,0,0,C 4001,22.5250,NaN,S
293,"Haas, Miss. Aloisia",294,0,3,female,24.0,0,0,349236,8.8500,NaN,S
819,"Skoog, Master. Karl Thorsten",820,0,3,male,10.0,3,2,347088,27.9000,NaN,S
810,"Alexander, Mr. William",811,0,3,male,26.0,0,0,3474,7.8875,NaN,S
757,"Bailey, Mr. Percy Andrew",758,0,2,male,18.0,0,0,29108,11.5000,NaN,S

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         891 non-null    object
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [97]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [99]:
df.describe(include='all')

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891,891.000000,891.000000,891.000000,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,891,NaN,NaN,NaN,2,NaN,NaN,NaN,681,NaN,147,3
top,"Harknett, Miss. Alice Phoebe",NaN,NaN,NaN,male,NaN,NaN,NaN,1601,NaN,C23 C25 C27,S
freq,1,NaN,NaN,NaN,577,NaN,NaN,NaN,7,NaN,4,644
mean,NaN,446.000000,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,NaN,257.353842,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,NaN,1.000000,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,NaN,223.500000,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,NaN,446.000000,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,NaN,668.500000,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,NaN,891.000000,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [100]:
df.describe(include='object')

                                Name   Sex Ticket        Cabin Embarked
count                            891   891    891          204      889
unique                           891     2    681          147        3
top     Harknett, Miss. Alice Phoebe  male   1601  C23 C25 C27        S
freq                               1   577      7            4      644

In [102]:
df['Sex']=='female'

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [103]:
df[df['Sex']=='female']

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0,0,2,347742,11.1333,NaN,S
9,"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,"Shelley, Mrs. William (Imanita Parrish Hall)",881,1,2,female,25.0,0,1,230433,26.0000,NaN,S
882,"Dahlberg, Miss. Gerda Ulrika",883,0,3,female,22.0,0,0,7552,10.5167,NaN,S
885,"Rice, Mrs. William (Margaret Norton)",886,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [108]:
df[(df['Sex']=='female')&(df['Survived']==1)]

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0,0,2,347742,11.1333,NaN,S
9,"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,"Abelson, Mrs. Samuel (Hannah Wizosky)",875,1,2,female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,"Najib, Miss. Adele Kiamie ""Jane""",876,1,3,female,15.0,0,0,2667,7.2250,NaN,C
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,1,female,56.0,0,1,11767,83.1583,C50,C
880,"Shelley, Mrs. William (Imanita Parrish Hall)",881,1,2,female,25.0,0,1,230433,26.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S

In [109]:
df[(df['Sex']=='male')&(df['Survived']==1)]

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,"Williams, Mr. Charles Eugene",18,1,2,male,NaN,0,0,244373,13.0000,NaN,S
21,"Beesley, Mr. Lawrence",22,1,2,male,34.0,0,0,248698,13.0000,D56,S
23,"Sloper, Mr. William Thompson",24,1,1,male,28.0,0,0,113788,35.5000,A6,S
36,"Mamee, Mr. Hanna",37,1,3,male,NaN,0,0,2677,7.2292,NaN,C
55,"Woolner, Mr. Hugh",56,1,1,male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,"Chip, Mr. Chang",839,1,3,male,32.0,0,0,1601,56.4958,NaN,S
839,"Marechal, Mr. Pierre",840,1,1,male,NaN,0,0,11774,29.7000,C47,C
857,"Daly, Mr. Peter Denis",858,1,1,male,51.0,0,0,113055,26.5500,E17,S
869,"Johnson, Master. Harold Theodor",870,1,3,male,4.0,1,1,347742,11.1333,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C

In [113]:
df[(df['Age']<12)&(df['Survived']==1)].shape[0]

39

In [114]:
df.describe(percentiles=[0.2,0.4])

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
20%,179.000000,0.000000,1.000000,19.000000,0.000000,0.000000,7.854200
40%,357.000000,0.000000,2.000000,25.000000,0.000000,0.000000,10.500000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200